### ISSUE TITLE
Access Point is Working BUT No PS5 Host

### ISSUE THREAD

**Issue by KsAmJ** [stooged/PS5-PI-Server#2]
I am using Pi 4 and updated it to a fresh build with your recent update.

The AP is visible, it joins on a PC or Phone BUT the page never loads 

tried 

http://ps5.local
https://ps5.local
http://ip adress

ONLY if i join another network and set the DNS to the Pi then the site loads

Also shouldn't playstaion.com be blocked? I can open playstation.com if I set the pi as DNS for another network.

**Comment by stooged** [comment]
on my pi4 i install raspberry pi os lite 64.

run the install script until it reboots.

once rebooted i can access the webpage using ps5.local or the pi ip address from my pc connected to my home network.
dns is only blocked if i set my dns to the pi ip address or if i am connecting through the wifi access point created during the install.

with my console i can connect it to the wifi ap of the pi and the userguide will load the exploit or i can connect it to my home network and set the dns in the console to the pi address and the userguide will load the exploit.

**Comment by KsAmJ** [comment]
I also use the same OS lite 64.

If I use the AP (NO DNS) how to access the exploit? because as i have mentioned all the addresses listed above not working if i just connect to Pi as AP.

The AP doesn't work the DNS does.

Also, why is the playstation.com site accessible if the pi used as a DNS for another network

**Comment by stooged** [comment]
if you connect to the ap all dns requests are handled by the pi so you do not need to set any dns.

ps5.local is the hostname which is automatically handled by mdns.

if you cant access ps5.local and you are connected to the ap setup in the pi then you connect to the gateway address which is statically set as 10.0.0.1

if you are using the pi as dns for another network and you can access playstation.com then something else on that network is resolving the ip or it is cached in the system trying to access the site.

if none of that works then the install script is simply not working for you, something has broken during the setup and considering it automates a lot of steps it could be a number of things.

**Comment by KsAmJ** [comment]
I tried 3 times using LAN instead of wifi to connect to the pi ssh leaving the wifi away of the equation for AP to operate in full

Still, the AP self-host doesn't work. 

Also tested with dieefrenbt Pi 3+B 

You may need to check yourself it this selfhost on the Pi Self AP works or not.

**Comment by KsAmJ** [comment]
3times meaning gone through a full wipe of the Pi and format and reinstall which was not a pleasant long experience.

**Comment by stooged** [comment]
i have changed it all to target armbian now, there were too many variations with other os builds.
armbian works on all 3 types of pi listed and seems to work the best in my tests.

for the rpi 3/4/400 you can use this cli image of ambian
https://redirect.armbian.com/region/NA/rpi4b/Bookworm_current

**Comment by KsAmJ** [comment]
Well just to let you know i have done all you mentioned with the new armbian image (2 times on Pi3 and Pi4) STILL the AP self-host doesn't work

Simply do it by joining the Pi AP from PS5 and try to go to the PS5 user guide after clearing the cache there. it doesn't load. and there is no way to open the ps5.local from there to as there is no browser. I tend to use offline hosts rather than online to avoid any risk and I really wanted this to work but no matter what it doesn't. Sadly I will shift to another host like Echo's one. Thanks anyway. good concept though. as would be easier to update than the ESP boards.

**Comment by ceedveed** [comment]
> Well just to let you know i have done all you mentioned with the new armbian image (2 times on Pi3 and Pi4) STILL the AP self-host doesn't work
> 
> Simply do it by joining the Pi AP from PS5 and try to go to the PS5 user guide after clearing the cache there. it doesn't load. and there is no way to open the ps5.local from there to as there is no browser. I tend to use offline hosts rather than online to avoid any risk and I really wanted this to work but no matter what it doesn't. Sadly I will shift to another host like Echo's one. Thanks anyway. good concept though. as would be easier to update than the ESP boards.

Have you fixed this? I tried Raspberry Lite 64 bit on a RPI4, setup with wifi automatically configured through the [Raspberry Pi imager](https://www.raspberrypi.com/software/). There is no PS5_WEB_AP I can connect to. However, I can access the samba share through `\\ps5.local\www`.

EDIT: Used [Armbian](https://www.armbian.com/rpi4b/), setup with ethernet connected, image written with [USBImager](https://gitlab.com/bztsrc/usbimager) as recommended by Armbian.  PS5_WEB_AP is now showing. I can also access samba share through `\\IPADDRESSofArmbian\www`. `http://ps5.local/` does not resolve, but `http://IPADDRESSofArmbian` does.


EDIT2: Unforunately user guide does not work. Also I had to set dnsmasq to use port 5353 because port 53 was being used. `systemctl status dnsmasq.service` was showing that port 53 was being used. `sudo lsof -i :53` showed that it was being used by systemd-resolved. I added `port=5353` to `/etc/dnsmasq.conf` with command `sudo nano /etc/dnsmasq.conf` Without these changes, connecting to the AP would not assign an address to the PS5.

EDIT3: Okay I got it to work. I mistakenly thought changing dnsmasq port would fix it, but DNS resolvers are looking for port 53. Instead I had to stop systemd-resolved from using port 53, so dnsmasq could use port 53. This [link](https://unix.stackexchange.com/questions/676942/free-up-port-53-on-ubuntu-so-custom-dns-server-can-use-it) helped.
Revise `/etc/systemd/resolved.conf` so that `DNSStubListener=no` by removing # and changing yes to no. I did not define DNS server in resolved.conf.
`sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf` to create symbolic link. Rebooted.
Now dnsmasq can use port 53. User guide finally shows on PS5. Additionally I updated the exploit files by copying from here: https://github.com/zecoxao/zecoxao.github.io/tree/main/idlesauce

EDIT4: additionally I needed to add the following to avoid a debug_log variable error:
```
include mime.types;
types {
    application/javascript js mjs;
} 
```
to `/etc/nginx/sites-available/default`
